[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'python312Packages.uvicorn']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2'
