[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'python312Packages.uvicorn']

[phases.build]
cmds = [
  'mkdir -p /app/models /app/static',
  'cp -r ./models/* /app/models/ || true',  # Updated to ./models/
  'cp -r ./static/* /app/static/ || true'
]

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  'source /opt/venv/bin/activate',
  'pip install -r requirements.txt'
]

[start]
cmd = 'source /opt/venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2'
